/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 56
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym__newline = 2,
  aux_sym_line_comment_token1 = 3,
  aux_sym_line_comment_token2 = 4,
  anon_sym_STAR = 5,
  aux_sym_line_comment_token3 = 6,
  sym_block_comment = 7,
  anon_sym_program = 8,
  anon_sym_define = 9,
  anon_sym_end = 10,
  anon_sym_mata = 11,
  anon_sym_COLON = 12,
  anon_sym_LBRACE = 13,
  anon_sym_RBRACE = 14,
  aux_sym__mata_line_token1 = 15,
  sym__mata_inline_content = 16,
  sym__mata_brace_content = 17,
  anon_sym_local = 18,
  anon_sym_loc = 19,
  anon_sym_global = 20,
  anon_sym_gl = 21,
  anon_sym_tempvar = 22,
  anon_sym_tempname = 23,
  anon_sym_tempfile = 24,
  anon_sym_by = 25,
  anon_sym_bysort = 26,
  anon_sym_bys = 27,
  anon_sym_quietly = 28,
  anon_sym_qui = 29,
  anon_sym_noisily = 30,
  anon_sym_noi = 31,
  anon_sym_capture = 32,
  anon_sym_cap = 33,
  anon_sym_sortpreserve = 34,
  sym__rest_of_line = 35,
  sym__line_start = 36,
  sym_source_file = 37,
  sym__line = 38,
  sym__statement = 39,
  sym_comment = 40,
  sym_line_comment = 41,
  sym_program_definition = 42,
  sym__program_line = 43,
  sym_mata_block = 44,
  sym__mata_line = 45,
  sym_macro_definition = 46,
  sym_command = 47,
  sym_prefix = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_program_definition_repeat1 = 50,
  aux_sym_mata_block_repeat1 = 51,
  aux_sym_mata_block_repeat2 = 52,
  aux_sym_macro_definition_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym__newline] = "_newline",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [aux_sym_line_comment_token2] = "line_comment_token2",
  [anon_sym_STAR] = "*",
  [aux_sym_line_comment_token3] = "line_comment_token3",
  [sym_block_comment] = "block_comment",
  [anon_sym_program] = "program",
  [anon_sym_define] = "define",
  [anon_sym_end] = "end",
  [anon_sym_mata] = "mata",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__mata_line_token1] = "_mata_line_token1",
  [sym__mata_inline_content] = "_mata_inline_content",
  [sym__mata_brace_content] = "_mata_brace_content",
  [anon_sym_local] = "local",
  [anon_sym_loc] = "loc",
  [anon_sym_global] = "global",
  [anon_sym_gl] = "gl",
  [anon_sym_tempvar] = "tempvar",
  [anon_sym_tempname] = "tempname",
  [anon_sym_tempfile] = "tempfile",
  [anon_sym_by] = "by",
  [anon_sym_bysort] = "bysort",
  [anon_sym_bys] = "bys",
  [anon_sym_quietly] = "quietly",
  [anon_sym_qui] = "qui",
  [anon_sym_noisily] = "noisily",
  [anon_sym_noi] = "noi",
  [anon_sym_capture] = "capture",
  [anon_sym_cap] = "cap",
  [anon_sym_sortpreserve] = "sortpreserve",
  [sym__rest_of_line] = "_rest_of_line",
  [sym__line_start] = "_line_start",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__statement] = "_statement",
  [sym_comment] = "comment",
  [sym_line_comment] = "line_comment",
  [sym_program_definition] = "program_definition",
  [sym__program_line] = "_program_line",
  [sym_mata_block] = "mata_block",
  [sym__mata_line] = "_mata_line",
  [sym_macro_definition] = "macro_definition",
  [sym_command] = "command",
  [sym_prefix] = "prefix",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_program_definition_repeat1] = "program_definition_repeat1",
  [aux_sym_mata_block_repeat1] = "mata_block_repeat1",
  [aux_sym_mata_block_repeat2] = "mata_block_repeat2",
  [aux_sym_macro_definition_repeat1] = "macro_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym__newline] = sym__newline,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [aux_sym_line_comment_token2] = aux_sym_line_comment_token2,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_line_comment_token3] = aux_sym_line_comment_token3,
  [sym_block_comment] = sym_block_comment,
  [anon_sym_program] = anon_sym_program,
  [anon_sym_define] = anon_sym_define,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_mata] = anon_sym_mata,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__mata_line_token1] = aux_sym__mata_line_token1,
  [sym__mata_inline_content] = sym__mata_inline_content,
  [sym__mata_brace_content] = sym__mata_brace_content,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_loc] = anon_sym_loc,
  [anon_sym_global] = anon_sym_global,
  [anon_sym_gl] = anon_sym_gl,
  [anon_sym_tempvar] = anon_sym_tempvar,
  [anon_sym_tempname] = anon_sym_tempname,
  [anon_sym_tempfile] = anon_sym_tempfile,
  [anon_sym_by] = anon_sym_by,
  [anon_sym_bysort] = anon_sym_bysort,
  [anon_sym_bys] = anon_sym_bys,
  [anon_sym_quietly] = anon_sym_quietly,
  [anon_sym_qui] = anon_sym_qui,
  [anon_sym_noisily] = anon_sym_noisily,
  [anon_sym_noi] = anon_sym_noi,
  [anon_sym_capture] = anon_sym_capture,
  [anon_sym_cap] = anon_sym_cap,
  [anon_sym_sortpreserve] = anon_sym_sortpreserve,
  [sym__rest_of_line] = sym__rest_of_line,
  [sym__line_start] = sym__line_start,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__statement] = sym__statement,
  [sym_comment] = sym_comment,
  [sym_line_comment] = sym_line_comment,
  [sym_program_definition] = sym_program_definition,
  [sym__program_line] = sym__program_line,
  [sym_mata_block] = sym_mata_block,
  [sym__mata_line] = sym__mata_line,
  [sym_macro_definition] = sym_macro_definition,
  [sym_command] = sym_command,
  [sym_prefix] = sym_prefix,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_program_definition_repeat1] = aux_sym_program_definition_repeat1,
  [aux_sym_mata_block_repeat1] = aux_sym_mata_block_repeat1,
  [aux_sym_mata_block_repeat2] = aux_sym_mata_block_repeat2,
  [aux_sym_macro_definition_repeat1] = aux_sym_macro_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_program] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_define] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mata] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__mata_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__mata_inline_content] = {
    .visible = false,
    .named = true,
  },
  [sym__mata_brace_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_global] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tempvar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tempname] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tempfile] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_by] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bysort] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bys] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_quietly] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_qui] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_noisily] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_noi] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_capture] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sortpreserve] = {
    .visible = true,
    .named = false,
  },
  [sym__rest_of_line] = {
    .visible = false,
    .named = true,
  },
  [sym__line_start] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__program_line] = {
    .visible = false,
    .named = true,
  },
  [sym_mata_block] = {
    .visible = true,
    .named = true,
  },
  [sym__mata_line] = {
    .visible = false,
    .named = true,
  },
  [sym_macro_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mata_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mata_block_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_name, 1, .inherited = true},
  [3] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [5] =
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '\n', 11,
        '\r', 1,
        '*', 14,
        '/', 5,
        ':', 20,
        'e', 36,
        '{', 21,
        '}', 22,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(29);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(29);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(32);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_line_comment_token3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_line_comment_token3);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_end);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_end);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__mata_line_token1);
      if (lookahead == 'd') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__mata_line_token1);
      if (lookahead == 'e') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__mata_line_token1);
      if (lookahead == 'n') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__mata_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__mata_inline_content);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(29);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__mata_inline_content);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(29);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__mata_inline_content);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__mata_inline_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__mata_brace_content);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__mata_brace_content);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__rest_of_line);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__rest_of_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'b', 1,
        'c', 2,
        'd', 3,
        'g', 4,
        'l', 5,
        'm', 6,
        'n', 7,
        'p', 8,
        'q', 9,
        's', 10,
        't', 11,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'y') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_by);
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(25);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_gl);
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(33);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_bys);
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_cap);
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'b') ADVANCE(37);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_loc);
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_noi);
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'g') ADVANCE(41);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_qui);
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(44);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(46);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_mata);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 43:
      if (lookahead == 'p') ADVANCE(53);
      END_STATE();
    case 44:
      if (lookahead == 'f') ADVANCE(54);
      if (lookahead == 'n') ADVANCE(55);
      if (lookahead == 'v') ADVANCE(56);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 51:
      if (lookahead == 'a') ADVANCE(62);
      END_STATE();
    case 52:
      if (lookahead == 'l') ADVANCE(63);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 54:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 55:
      if (lookahead == 'a') ADVANCE(66);
      END_STATE();
    case 56:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_bysort);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_define);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_global);
      END_STATE();
    case 61:
      if (lookahead == 'y') ADVANCE(69);
      END_STATE();
    case 62:
      if (lookahead == 'm') ADVANCE(70);
      END_STATE();
    case 63:
      if (lookahead == 'y') ADVANCE(71);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(73);
      END_STATE();
    case 66:
      if (lookahead == 'm') ADVANCE(74);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_capture);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_noisily);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_program);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_quietly);
      END_STATE();
    case 72:
      if (lookahead == 's') ADVANCE(76);
      END_STATE();
    case 73:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_tempvar);
      END_STATE();
    case 76:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_tempfile);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_tempname);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(80);
      END_STATE();
    case 80:
      if (lookahead == 'v') ADVANCE(81);
      END_STATE();
    case 81:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_sortpreserve);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 9, .external_lex_state = 1},
  [2] = {.lex_state = 9, .external_lex_state = 1},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 9, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 1},
  [6] = {.lex_state = 0, .external_lex_state = 1},
  [7] = {.lex_state = 0, .external_lex_state = 1},
  [8] = {.lex_state = 0, .external_lex_state = 1},
  [9] = {.lex_state = 9, .external_lex_state = 1},
  [10] = {.lex_state = 0, .external_lex_state = 1},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 24},
  [15] = {.lex_state = 24},
  [16] = {.lex_state = 24},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 24},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 15},
  [42] = {.lex_state = 9},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [aux_sym_line_comment_token1] = ACTIONS(1),
    [aux_sym_line_comment_token2] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(1),
    [anon_sym_program] = ACTIONS(1),
    [anon_sym_define] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_mata] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_loc] = ACTIONS(1),
    [anon_sym_global] = ACTIONS(1),
    [anon_sym_gl] = ACTIONS(1),
    [anon_sym_tempvar] = ACTIONS(1),
    [anon_sym_tempname] = ACTIONS(1),
    [anon_sym_tempfile] = ACTIONS(1),
    [anon_sym_by] = ACTIONS(1),
    [anon_sym_bysort] = ACTIONS(1),
    [anon_sym_bys] = ACTIONS(1),
    [anon_sym_quietly] = ACTIONS(1),
    [anon_sym_qui] = ACTIONS(1),
    [anon_sym_noisily] = ACTIONS(1),
    [anon_sym_noi] = ACTIONS(1),
    [anon_sym_capture] = ACTIONS(1),
    [anon_sym_cap] = ACTIONS(1),
    [anon_sym_sortpreserve] = ACTIONS(1),
    [sym__line_start] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(51),
    [sym__line] = STATE(4),
    [sym__statement] = STATE(53),
    [sym_comment] = STATE(53),
    [sym_line_comment] = STATE(32),
    [sym_program_definition] = STATE(53),
    [sym_mata_block] = STATE(53),
    [sym_macro_definition] = STATE(53),
    [sym_command] = STATE(53),
    [sym_prefix] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(2)] = {
    [sym__line] = STATE(2),
    [sym__statement] = STATE(53),
    [sym_comment] = STATE(53),
    [sym_line_comment] = STATE(32),
    [sym_program_definition] = STATE(53),
    [sym_mata_block] = STATE(53),
    [sym_macro_definition] = STATE(53),
    [sym_command] = STATE(53),
    [sym_prefix] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym__newline] = ACTIONS(32),
    [aux_sym_line_comment_token1] = ACTIONS(35),
    [aux_sym_line_comment_token2] = ACTIONS(38),
    [sym_block_comment] = ACTIONS(41),
    [anon_sym_program] = ACTIONS(44),
    [anon_sym_mata] = ACTIONS(47),
    [anon_sym_local] = ACTIONS(50),
    [anon_sym_loc] = ACTIONS(50),
    [anon_sym_global] = ACTIONS(50),
    [anon_sym_gl] = ACTIONS(50),
    [anon_sym_tempvar] = ACTIONS(53),
    [anon_sym_tempname] = ACTIONS(53),
    [anon_sym_tempfile] = ACTIONS(53),
    [anon_sym_by] = ACTIONS(56),
    [anon_sym_bysort] = ACTIONS(56),
    [anon_sym_bys] = ACTIONS(56),
    [anon_sym_quietly] = ACTIONS(56),
    [anon_sym_qui] = ACTIONS(56),
    [anon_sym_noisily] = ACTIONS(56),
    [anon_sym_noi] = ACTIONS(56),
    [anon_sym_capture] = ACTIONS(56),
    [anon_sym_cap] = ACTIONS(56),
    [anon_sym_sortpreserve] = ACTIONS(56),
    [sym__line_start] = ACTIONS(59),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(37),
    [sym_comment] = STATE(37),
    [sym_line_comment] = STATE(32),
    [sym_program_definition] = STATE(37),
    [sym__program_line] = STATE(6),
    [sym_mata_block] = STATE(37),
    [sym_macro_definition] = STATE(37),
    [sym_command] = STATE(37),
    [sym_prefix] = STATE(35),
    [aux_sym_program_definition_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(62),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_end] = ACTIONS(64),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym__line] = STATE(2),
    [sym__statement] = STATE(53),
    [sym_comment] = STATE(53),
    [sym_line_comment] = STATE(32),
    [sym_program_definition] = STATE(53),
    [sym_mata_block] = STATE(53),
    [sym_macro_definition] = STATE(53),
    [sym_command] = STATE(53),
    [sym_prefix] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(66),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(68),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(37),
    [sym_comment] = STATE(37),
    [sym_line_comment] = STATE(32),
    [sym_program_definition] = STATE(37),
    [sym__program_line] = STATE(7),
    [sym_mata_block] = STATE(37),
    [sym_macro_definition] = STATE(37),
    [sym_command] = STATE(37),
    [sym_prefix] = STATE(35),
    [aux_sym_program_definition_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(70),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_end] = ACTIONS(72),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(37),
    [sym_comment] = STATE(37),
    [sym_line_comment] = STATE(32),
    [sym_program_definition] = STATE(37),
    [sym__program_line] = STATE(8),
    [sym_mata_block] = STATE(37),
    [sym_macro_definition] = STATE(37),
    [sym_command] = STATE(37),
    [sym_prefix] = STATE(35),
    [aux_sym_program_definition_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(74),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_end] = ACTIONS(76),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(37),
    [sym_comment] = STATE(37),
    [sym_line_comment] = STATE(32),
    [sym_program_definition] = STATE(37),
    [sym__program_line] = STATE(8),
    [sym_mata_block] = STATE(37),
    [sym_macro_definition] = STATE(37),
    [sym_command] = STATE(37),
    [sym_prefix] = STATE(35),
    [aux_sym_program_definition_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(74),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_end] = ACTIONS(78),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(37),
    [sym_comment] = STATE(37),
    [sym_line_comment] = STATE(32),
    [sym_program_definition] = STATE(37),
    [sym__program_line] = STATE(8),
    [sym_mata_block] = STATE(37),
    [sym_macro_definition] = STATE(37),
    [sym_command] = STATE(37),
    [sym_prefix] = STATE(35),
    [aux_sym_program_definition_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(80),
    [sym__newline] = ACTIONS(83),
    [aux_sym_line_comment_token1] = ACTIONS(86),
    [aux_sym_line_comment_token2] = ACTIONS(89),
    [sym_block_comment] = ACTIONS(92),
    [anon_sym_program] = ACTIONS(95),
    [anon_sym_end] = ACTIONS(98),
    [anon_sym_mata] = ACTIONS(100),
    [anon_sym_local] = ACTIONS(103),
    [anon_sym_loc] = ACTIONS(103),
    [anon_sym_global] = ACTIONS(103),
    [anon_sym_gl] = ACTIONS(103),
    [anon_sym_tempvar] = ACTIONS(106),
    [anon_sym_tempname] = ACTIONS(106),
    [anon_sym_tempfile] = ACTIONS(106),
    [anon_sym_by] = ACTIONS(109),
    [anon_sym_bysort] = ACTIONS(109),
    [anon_sym_bys] = ACTIONS(109),
    [anon_sym_quietly] = ACTIONS(109),
    [anon_sym_qui] = ACTIONS(109),
    [anon_sym_noisily] = ACTIONS(109),
    [anon_sym_noi] = ACTIONS(109),
    [anon_sym_capture] = ACTIONS(109),
    [anon_sym_cap] = ACTIONS(109),
    [anon_sym_sortpreserve] = ACTIONS(109),
    [sym__line_start] = ACTIONS(112),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(115), 5,
      sym__line_start,
      ts_builtin_sym_end,
      sym__newline,
      aux_sym_line_comment_token1,
      sym_block_comment,
    ACTIONS(117), 21,
      aux_sym_line_comment_token2,
      anon_sym_program,
      anon_sym_mata,
      anon_sym_local,
      anon_sym_loc,
      anon_sym_global,
      anon_sym_gl,
      anon_sym_tempvar,
      anon_sym_tempname,
      anon_sym_tempfile,
      anon_sym_by,
      anon_sym_bysort,
      anon_sym_bys,
      anon_sym_quietly,
      anon_sym_qui,
      anon_sym_noisily,
      anon_sym_noi,
      anon_sym_capture,
      anon_sym_cap,
      anon_sym_sortpreserve,
      sym_identifier,
  [31] = 2,
    ACTIONS(121), 4,
      sym__line_start,
      sym__newline,
      aux_sym_line_comment_token1,
      sym_block_comment,
    ACTIONS(119), 22,
      aux_sym_line_comment_token2,
      anon_sym_program,
      anon_sym_end,
      anon_sym_mata,
      anon_sym_local,
      anon_sym_loc,
      anon_sym_global,
      anon_sym_gl,
      anon_sym_tempvar,
      anon_sym_tempname,
      anon_sym_tempfile,
      anon_sym_by,
      anon_sym_bysort,
      anon_sym_bys,
      anon_sym_quietly,
      anon_sym_qui,
      anon_sym_noisily,
      anon_sym_noi,
      anon_sym_capture,
      anon_sym_cap,
      anon_sym_sortpreserve,
      sym_identifier,
  [62] = 3,
    ACTIONS(123), 1,
      anon_sym_end,
    ACTIONS(125), 1,
      aux_sym__mata_line_token1,
    STATE(14), 2,
      sym__mata_line,
      aux_sym_mata_block_repeat2,
  [73] = 4,
    ACTIONS(127), 1,
      sym__newline,
    ACTIONS(129), 1,
      anon_sym_COLON,
    ACTIONS(131), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      sym__mata_inline_content,
  [86] = 3,
    ACTIONS(135), 1,
      anon_sym_end,
    ACTIONS(137), 1,
      aux_sym__mata_line_token1,
    STATE(13), 2,
      sym__mata_line,
      aux_sym_mata_block_repeat2,
  [97] = 3,
    ACTIONS(125), 1,
      aux_sym__mata_line_token1,
    ACTIONS(140), 1,
      anon_sym_end,
    STATE(13), 2,
      sym__mata_line,
      aux_sym_mata_block_repeat2,
  [108] = 3,
    ACTIONS(125), 1,
      aux_sym__mata_line_token1,
    ACTIONS(140), 1,
      anon_sym_end,
    STATE(16), 2,
      sym__mata_line,
      aux_sym_mata_block_repeat2,
  [119] = 3,
    ACTIONS(125), 1,
      aux_sym__mata_line_token1,
    ACTIONS(142), 1,
      anon_sym_end,
    STATE(13), 2,
      sym__mata_line,
      aux_sym_mata_block_repeat2,
  [130] = 3,
    ACTIONS(123), 1,
      sym__mata_inline_content,
    ACTIONS(144), 1,
      sym__newline,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
  [140] = 3,
    ACTIONS(123), 1,
      anon_sym_RBRACE,
    ACTIONS(148), 1,
      sym__mata_brace_content,
    STATE(21), 1,
      aux_sym_mata_block_repeat1,
  [150] = 3,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(152), 1,
      sym__newline,
    STATE(23), 1,
      aux_sym_macro_definition_repeat1,
  [160] = 3,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      sym__mata_brace_content,
    STATE(20), 1,
      aux_sym_mata_block_repeat1,
  [170] = 3,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    ACTIONS(159), 1,
      sym__mata_brace_content,
    STATE(20), 1,
      aux_sym_mata_block_repeat1,
  [180] = 3,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    ACTIONS(161), 1,
      sym__mata_brace_content,
    STATE(24), 1,
      aux_sym_mata_block_repeat1,
  [190] = 3,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(166), 1,
      sym__newline,
    STATE(23), 1,
      aux_sym_macro_definition_repeat1,
  [200] = 3,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    ACTIONS(159), 1,
      sym__mata_brace_content,
    STATE(20), 1,
      aux_sym_mata_block_repeat1,
  [210] = 2,
    ACTIONS(168), 1,
      sym__newline,
    ACTIONS(170), 1,
      sym__rest_of_line,
  [217] = 2,
    ACTIONS(172), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_define,
  [224] = 2,
    ACTIONS(150), 1,
      sym_identifier,
    STATE(19), 1,
      aux_sym_macro_definition_repeat1,
  [231] = 2,
    ACTIONS(176), 1,
      sym__newline,
    ACTIONS(178), 1,
      sym__rest_of_line,
  [238] = 2,
    ACTIONS(180), 1,
      sym__newline,
    ACTIONS(182), 1,
      sym__rest_of_line,
  [245] = 1,
    ACTIONS(184), 2,
      sym__newline,
      sym_identifier,
  [250] = 1,
    ACTIONS(186), 2,
      anon_sym_end,
      aux_sym__mata_line_token1,
  [255] = 1,
    ACTIONS(188), 1,
      sym__newline,
  [259] = 1,
    ACTIONS(190), 1,
      sym__newline,
  [263] = 1,
    ACTIONS(192), 1,
      anon_sym_STAR,
  [267] = 1,
    ACTIONS(194), 1,
      sym_identifier,
  [271] = 1,
    ACTIONS(196), 1,
      sym__newline,
  [275] = 1,
    ACTIONS(198), 1,
      sym__newline,
  [279] = 1,
    ACTIONS(200), 1,
      sym__newline,
  [283] = 1,
    ACTIONS(202), 1,
      sym__newline,
  [287] = 1,
    ACTIONS(204), 1,
      sym__newline,
  [291] = 1,
    ACTIONS(206), 1,
      aux_sym_line_comment_token3,
  [295] = 1,
    ACTIONS(208), 1,
      sym_identifier,
  [299] = 1,
    ACTIONS(210), 1,
      sym_identifier,
  [303] = 1,
    ACTIONS(212), 1,
      sym__newline,
  [307] = 1,
    ACTIONS(214), 1,
      sym_identifier,
  [311] = 1,
    ACTIONS(216), 1,
      sym__newline,
  [315] = 1,
    ACTIONS(218), 1,
      sym__newline,
  [319] = 1,
    ACTIONS(220), 1,
      sym__newline,
  [323] = 1,
    ACTIONS(222), 1,
      sym__newline,
  [327] = 1,
    ACTIONS(224), 1,
      sym__newline,
  [331] = 1,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
  [335] = 1,
    ACTIONS(228), 1,
      sym__newline,
  [339] = 1,
    ACTIONS(230), 1,
      sym__newline,
  [343] = 1,
    ACTIONS(232), 1,
      sym__newline,
  [347] = 1,
    ACTIONS(234), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 31,
  [SMALL_STATE(11)] = 62,
  [SMALL_STATE(12)] = 73,
  [SMALL_STATE(13)] = 86,
  [SMALL_STATE(14)] = 97,
  [SMALL_STATE(15)] = 108,
  [SMALL_STATE(16)] = 119,
  [SMALL_STATE(17)] = 130,
  [SMALL_STATE(18)] = 140,
  [SMALL_STATE(19)] = 150,
  [SMALL_STATE(20)] = 160,
  [SMALL_STATE(21)] = 170,
  [SMALL_STATE(22)] = 180,
  [SMALL_STATE(23)] = 190,
  [SMALL_STATE(24)] = 200,
  [SMALL_STATE(25)] = 210,
  [SMALL_STATE(26)] = 217,
  [SMALL_STATE(27)] = 224,
  [SMALL_STATE(28)] = 231,
  [SMALL_STATE(29)] = 238,
  [SMALL_STATE(30)] = 245,
  [SMALL_STATE(31)] = 250,
  [SMALL_STATE(32)] = 255,
  [SMALL_STATE(33)] = 259,
  [SMALL_STATE(34)] = 263,
  [SMALL_STATE(35)] = 267,
  [SMALL_STATE(36)] = 271,
  [SMALL_STATE(37)] = 275,
  [SMALL_STATE(38)] = 279,
  [SMALL_STATE(39)] = 283,
  [SMALL_STATE(40)] = 287,
  [SMALL_STATE(41)] = 291,
  [SMALL_STATE(42)] = 295,
  [SMALL_STATE(43)] = 299,
  [SMALL_STATE(44)] = 303,
  [SMALL_STATE(45)] = 307,
  [SMALL_STATE(46)] = 311,
  [SMALL_STATE(47)] = 315,
  [SMALL_STATE(48)] = 319,
  [SMALL_STATE(49)] = 323,
  [SMALL_STATE(50)] = 327,
  [SMALL_STATE(51)] = 331,
  [SMALL_STATE(52)] = 335,
  [SMALL_STATE(53)] = 339,
  [SMALL_STATE(54)] = 343,
  [SMALL_STATE(55)] = 347,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__program_line, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__program_line, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_mata_block_repeat2, 2, 0, 0),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mata_block_repeat2, 2, 0, 0), SHIFT_REPEAT(40),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 2, 0, 3),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_mata_block_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mata_block_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_definition_repeat1, 2, 0, 4), SHIFT_REPEAT(30),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_definition_repeat1, 2, 0, 4),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 0, 2),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_definition, 2, 0, 2),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, 0, 1),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_definition_repeat1, 1, 0, 1),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__mata_line, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 3, 0, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 3, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mata_block, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 3, 0, 2),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 1, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 4, 0, 2),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 2),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mata_block, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mata_block, 4, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 4, 0, 5),
  [226] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 5, 0, 5),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mata_block, 5, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__line_start = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__line_start] = sym__line_start,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__line_start] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_stata_external_scanner_create(void);
void tree_sitter_stata_external_scanner_destroy(void *);
bool tree_sitter_stata_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_stata_external_scanner_serialize(void *, char *);
void tree_sitter_stata_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_stata(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_stata_external_scanner_create,
      tree_sitter_stata_external_scanner_destroy,
      tree_sitter_stata_external_scanner_scan,
      tree_sitter_stata_external_scanner_serialize,
      tree_sitter_stata_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "stata",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
